### ISSUE TITLE
Probability for number of units would be a fun addition

### ISSUE THREAD

**Issue by Makstuff** [dsimmer/production-surge-calc#1]
Just a thought in case you're motivated to keep working on this.

If you just want a large amount of chump blockers, the pure number of units can be much more relevant than the exact type of units. Currently you can calculate that manually by adding up all the percentages for x units. Example for 4 mana 3 boardspace: The probability to get 2 or more units is 33.33+29.17+12.5=75%.

Anyway the tool is great as-is and fun to play around with, thanks for making!

**Comment by Makstuff** [comment]
On second thought, the probability for number of elusive turrets specifically would also be nice since they are probably the most important ones for closing out the game.

**Comment by dsimmer** [comment]
done!

**Comment by Makstuff** [comment]
Cool, thanks! Whats the url of this project again, I don't remember it and cant find it anywhere here 🤔

**Comment by dsimmer** [comment]
It is at https://dsimmer.github.io/production-surge-calc/
